### ISSUE TITLE
Theory behind the implementation?

### ISSUE THREAD

**Issue by pligor** [ywpkwon/siamese_tf_mnist#1]
In particular looking for explanations/link for loss_with_spring function (loss_with_step is not used)

And in general is there a blog post that links your implementation with the logic behind it?

In fact, there is a relative answer here: Contrastive loss: https://stackoverflow.com/a/38270293/720484
But your implementation is a little bit different and would be good to have some explanation of why the details differ from a simple contrastive loss. Thank you

**Comment by ywpkwon** [comment]
Hello, pligor,

Thanks for your question, and sorry for late response.
I am interpreting the `contrastive loss` and `loss_with_spring` are quite the same. Could you explain where the two functions are different?

Basically, I meant the contrastive loss. The naming `spring` comes from the paper:
http://yann.lecun.com/exdb/publis/pdf/hadsell-chopra-lecun-06.pdf

It has a physical explanation of contractive loss, which was nice to me.

**Comment by pligor** [comment]
Thanks for sharing
