### ISSUE TITLE
diffrence between two types of loss

### ISSUE THREAD

**Issue by clover978** [ywpkwon/siamese_tf_mnist#5]
Hi, Thanks for your work.
I noticed that you have implemented two loss functions  in inference.py. loss_with_spring and loss_with_step.
The default one is loss_with_spring. However, by my understanding, loss_with_step corresponds to definition of contrastive-loss, which is used by caffe example.
Besides, the default margin value is set to 5,which is much larger than other's implementation. Could you please share your insight with me.

**Comment by BlueWinters** [comment]
I have the same question , would like to tell me something about it?
Also, I train the model, but I can not get the result like result.png... what is happening ...
